Cleanup kscripts
paug/video-tools pull request #3
Opened 2020-02-22 16:26 UTC by martinbonnin

2020-02-23 14:17 UTC, djavan-bertrand requested changes

2020-02-23 14:17 UTC, djavan-bertrand commented on kscripts/videotool.kts
> +    execOrDie("dd",
On a besoin de couper alors que ffmpeg va le faire ?

2020-02-23 14:17 UTC, djavan-bertrand commented on kscripts/videotool.kts
> +            "-b:v", "3M",
je suis à 15M dans le script python. Quelle valeur on choisit ?

2020-02-23 14:17 UTC, djavan-bertrand commented on kscripts/videotool.kts
> +    execOrDie("ffmpeg",
Est-ce qu'on ne peut pas merger les appels ffmpeg en un seul pour gagner du temps ?

2020-02-23 14:17 UTC, djavan-bertrand commented on kscripts/videotool.kts
> +    execOrDie("ffmpeg",
La reponse est oui on peut. La vrai question c'est est-ce que 2 appels à ffmpeg est plus long qu'un seul :)

2020-02-23 14:17 UTC, djavan-bertrand commented on kscripts/videotool.kts
> +    execOrDie("ffmpeg",
Voila la commande ffmpeg du script python:
```
raw_cmd = '''ffmpeg -loop 1 -framerate 24 -t 5 -i {intro} -f lavfi -t 0.1 \
        -i anullsrc -i {video} -filter_complex \
        "[0:v]format=pix_fmts=yuva420p,fade=t=out:st=3:d=1:alpha=1[intro];\
        [2:v]trim={trim_start}{trim_end},setpts=PTS-STARTPTS[contentNotAligned];\
        [contentNotAligned]setpts=PTS+3/TB[content];\
        [content][intro]overlay[merged];\
        [2:a]atrim={trim_start}{trim_end},asetpts=PTS-STARTPTS[audioNotAligned];\
        [audioNotAligned]pan=mono|{audio_channel}[audioMono];\
        [audioMono]asetpts=PTS+3/TB[audio];\
        [merged][audio]concat=n=1:v=1:a=1" \
        -b:v 15M {output}'''
```

2020-02-23 14:54 UTC, martinbonnin commented on kscripts/videotool.kts
> +            "-b:v", "3M",
9 ? :)

2020-02-23 14:54 UTC, martinbonnin commented on kscripts/videotool.kts
> +    execOrDie("dd",
cf plus bas

2020-02-23 14:55 UTC, martinbonnin commented on kscripts/videotool.kts
> +    execOrDie("ffmpeg",
Ce que j'ai essayé un maximum, c'est de ne pas réencoder la vidéo. L'avantage c'est que ça évite toute perte de qualité et aussi que c'est beaucoup plus rapide (qqs secondes pour une vidéo de 2GB).

L'inconvénient c'est que ça plus de manipulations dans tous les sens...

2020-05-26 16:29 UTC, martinbonnin commented
Obsolete

2020-05-26 16:29 UTC, closed without merging